language: java
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./.travis/before-deploy.sh"
- "./.travis/deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_TOKEN
  file_glob: true
  file:
  - chmod +x ./cd/before-deploy.sh
  - chmod +x ./cd/deploy.sh
  - "./Core/target/wildbot-core-*.jar"
  - "./Bootstrap/target/wildbot-bootstrap-*.jar"
  skip_cleanup: true
  name: WildBot v$TRAVIS_TAG
  on:
    tags: true
    branch: master