language: java
sudo: false
install: true
script:
- 'clean test package install javadoc:javadoc'
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_DEPLOY_TOKEN
#  on:
#    branch: master
